# Generated by Django 2.2.5 on 2020-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
